version: "3.8"
services:
    frontend:
        build: ./jobapp
        container_name: frontendtest
        ports:
            - "5173:5173"
        volumes:
            - ./jobapp:/app
            - /app/node_modules
